on:
  push:
    branches: [main]
    tags: ["*.*.*"]
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
    - run: dotnet build --configuration Release
    - run: dotnet test
    - run: dotnet pack --configuration Release
    - run: |
        dotnet nuget push src/**/*.nupkg \
          --source https://nuget.pkg.github.com/unmango/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }}
